# PATH TO DATASET
dataset_root_directory: 'data/ADNI/'
# RANGE OF RANDOM ROTATION, 0 WILL TURN OFF RANDOM ROTATION, ENTER VALUE IN DEGREES
rotation_limit_in_degrees: 0
# TYPE OF GAMMA CORRECTION, 0 WILL TURN OFF GAMMA CORRECTION, 1: RANDOM VALUE FROM (0.9, 1.1), 2: RANDOM VALUE (0.8, 1.2), 3: RANDOM VALUE (0.7, 1.3)
gamma_correction_type: 2
# NUMBER OF NOT IMPROVING EPOCH TO LOWER LR
n_epoch_to_decrease_lr: 5
# NUMBER OF NOT IMPROVING EPOCH TO STOP LEARNING PHASE AND SAVE MODEL
n_epoch_to_stop: 8
# PATH TO CHECKPOINT, DELETE OR COMMENT THIS LINE IF YOU WANT TO START FROM ZERO
checkpoint_patch: "outputs/pre_trained/gamma_rotate_combination.pth"